# Generated by Django 5.0.3 on 2024-03-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationMASSCCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, default=298.0, max_digits=5)),
                ('seed', models.IntegerField(default=2104)),
                ('gas', models.CharField(choices=[('Helium', 'He'), ('Nitrogen', 'N2 ')], default='Helium', max_length=8)),
                ('ccs_avg', models.FloatField()),
                ('ccs_err', models.FloatField()),
                ('time_execution', models.FloatField()),
                ('job_id', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('ip_client', models.CharField(max_length=100)),
                ('successful', models.CharField(max_length=10)),
                ('err', models.CharField(max_length=255)),
                ('status_ip', models.CharField(max_length=10)),
                ('country_ip', models.CharField(max_length=32)),
                ('country_code_ip', models.CharField(max_length=10)),
                ('city_ip', models.CharField(max_length=32)),
            ],
        ),
    ]
